# This docker-compose is for docker-compose version 1.8
# Run docker-compose to check your docker version
# When your docker is > 1.8 use the newer docker-compose file as if contains
# several advantages.
version: "2.0"
services:
  elasticsearch:
    # image: elasticsearch:latest
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
      # - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - honeytrap
  kibana:
    # image: kibana:latest
    image: docker.elastic.co/kibana/kibana:5.6.4
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - XPACK_SECURITY_ENABLED=false
      # - ELASTICSEARCH_USER=elastic
      # - ELASTICSEARCH_PASSWORD=changeme
    networks:
      - honeytrap
networks:
  honeytrap:
    external: true
